version: 2.1
executors:
  node14:
    docker:
    - image: circleci/node:14
    environment:
      NPM_CONFIG_PREFIX: ~/.npm-global

orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2

commands:
  setup:
    steps:
    - checkout
    # - restore_cache:
    #     keys:
    #     - v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
    - run:
        name: install latest npm
        command: sudo npm -g install npm
    - run:
        name: Installing Dependencies
        command: npm ci
    # - save_cache:
    #     paths:
    #     - node_modules
    #     key: v1-dependencies-{{ arch }}-{{ checksum "package-lock.json" }}
    - run:
        name: prepare test git user
        command: git config --global user.email "circleci@example.com" && git config --global user.name "CircleCi Build"

jobs:
  build:
    executor: node14
    steps:
    - setup
    - run: mkdir junit
    - run:
        name: Lint
        command: npm run lint
    - puppeteer/install
    - run:
        name: Set CHROME_PATH
        command: export CHROME_PATH=`find /home/circleci/project/node_modules -name chrome`
    - run:
        name: Test
        command: npm run test
    - store_test_results:
        path: junit
    - store_artifacts:
        path: junit
  semantic-release:
    executor: node14
    steps:
      - setup
      - run:
          name: revert changes to package-lock.json
          command: git checkout -- package-lock.json
      - run:
          name: Semantic Release
          command: npm run semantic-release

workflows:
  version: 2
  build:
    jobs:
    - build
    - semantic-release:
        context: Project Helix
        requires:
          - build
        filters:
          branches:
            only: main
