name: Branch Release
on: push

jobs:
  branch-release:
    runs-on: ubuntu-latest
    if: "${{ !endsWith(github.ref, '/main') && !contains(github.event.head_commit.message, '[skip ci]') }}"
    steps:
      - name: Checkout sidekick repo
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH-KEY }}
      - name: Checkout dist repo
        uses: actions/checkout@v2
        with:
          repository: rofe/helix-sidekick
          ref: sandbox
          path: dist
      - name: Copy changes to dist repo and create branch commit
        run: |
          cp src/sidekick/app.* dist/src/sidekick/
          cd dist
          # generate dist branch name
          IFS='/' read -ra temp <<< "${{ github.ref }}"
          distbranch=sidekick-${temp[2]}
          # create and/or switch to dist branch and apply changes
          git switch ${distbranch} || git checkout -b ${distbranch}
          git add src/sidekick/*
          if [ "`git status -s`" != "" ]; then
            # push changes to dist branch
            git config user.name ${{ github.actor }}
            git config user.password ${{ secrets.PAT }}
            git config user.email ${{ github.actor }}@users.noreply.github.com
            git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
            git commit -m"chore(sidekick): branch release [skip ci]"
            git push origin ${distbranch}
          fi
