name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: "${{ !contains(github.event.head_commit.message, '[skip ci]') }}"
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH-KEY }}
      - name: Checkout target repo
        uses: actions/checkout@v2
        with:
          repository: adobe/helix-pages
          path: _target
      - name: Copy files from source to target repo
        run: |
          cp src/sidekick/app.* _target/tools/sidekick/
      - name: Create branch commit and pull request in target repo
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore(sidekick): new release candidate [skip ci]"
          token: ${{ secrets.PAT }}
          path: _target
          branch: sidekick-rc
          branch-suffix: short-commit-hash
          delete-branch: true
          title: Sidekick Release Candidate
          body: This PR has been auto-generated from https://github.com/adobe/helix-sidekick/.
