name: Release
on:
  push:
    branches:
      - main

jobs:
  checkout:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH-KEY }}
  release:
    runs-on: ubuntu-latest
    needs: checkout
    if: "${{ !contains(github.event.head_commit.message, '[skip ci]') }}"
    steps:
      - name: Checkout dist repo
        uses: actions/checkout@v2
        with:
          repository: adobe/helix-pages
          path: dist
      - name: Copy files to dist repo
        run: |
          cp src/sidekick/app.* dist/tools/sidekick/
      - name: Create pull request in dist repo
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore(sidekick): new release [skip ci]"
          token: ${{ secrets.PAT }}
          path: dist
          branch: sidekick
          branch-suffix: short-commit-hash
          delete-branch: true
          title: Helix Sidekick Release
          body: This PR has been auto-generated from https://github.com/adobe/helix-sidekick/ to update Helix Sidekick.
