name: Release
on:
  push
    branches:
      - 'branch-release'

jobs:
  checkout:
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH-KEY }}
  branch-release:
    runs-on: ubuntu-latest
    needs: checkout
    if: "!endsWith(github.ref, '/main') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Switch to branch
        run: |
          IFS=';' read -ra temp <<< "${{ github.ref }}"
          echo github.ref: ---${temp[2]}---
          echo `git branch --show-current`
          git checkout $GH_BRANCH
      - name: Checkout dist repo
        uses: actions/checkout@v2
        with:
          repository: rofe/helix-sidekick
          path: dist
      - name: Copy files to dist repo
        run: |
          # create dist branch name
          IFS=';' read -ra temp <<< "${{ github.ref }}"
          echo github.ref: ---${temp[2]}---
          distbranch=sidekick-${temp[2]}
          # create and/or switch to dist branch
          git switch ${distbranch} || git checkout -b sidekick-${temp[2]}
          cp src/sidekick/app.* dist/src/sidekick/
          if [ "`git status -s`" != "" ]; then
            # push changes to dist branch
            git add dist/src/sidekick/*
            git commit -m"chore(sidekick): branch release [skip ci]"
            git push origin ${distbranch}
          fi
  release:
    runs-on: ubuntu-latest
    needs: checkout
    if: "endsWith(github.ref, '/main') && !contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout dist repo
        uses: actions/checkout@v2
        with:
          repository: adobe/helix-pages
          path: dist
      - name: Copy files to dist repo
        run: |
          cp src/sidekick/app.* dist/tools/sidekick/
      - name: Create pull request in dist repo
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore(sidekick): new release [skip ci]"
          token: ${{ secrets.PAT }}
          path: dist
          branch: sidekick
          branch-suffix: short-commit-hash
          delete-branch: true
          title: Helix Sidekick Release
          body: This PR has been auto-generated from https://github.com/adobe/helix-sidekick/ to update Helix Sidekick.
