name: Semantic Release
on:
  push:
    branches:
      - 'release-test'

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.SSH-KEY }}
          ref: main
      - name: Checkout dist repo
        uses: actions/checkout@v2
        with:
          repository: rofe/helix-sidekick
          ssh-key: ${{ secrets.SSH-KEY }}
          ref: sandbox
          path: dist
      - name: Create commit in dist repo
        run: |
          cp src/sidekick/app.* dist/src/sidekick/
          cd dist/src/sidekick
          git config --global user.email "rofe@adobe.com"
          git config --global user.name "rofe"
      - name: Create pull request in dist repo
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "chore(release): new sidekick version"
          token: ${{ secrets.PAT }}
          path: dist
          delete-branch: true
          title: Helix Sidekick Release
          body: New version of [Helix Sidekick](https://github.com/adobe/helix-sidekick/)
